// mis-react/src/components/Cont.jsx
import React from 'react'
import axios from 'axios'
import Contcss from '../css/cont.scss'

export default class Cont extends React.Component{
    constructor(props) {
        super(props)
        this.state = {
            isRoot: true,
            creating: false,
            adminList: [],
            hasAccount: '',
            adminData: {
                email: '',
                pwd: ''
            }
        }
    }

    signUpPageShow () {
        this.setState({
            creating: true
        })
    }

    signUpPageHide () {
        const admin = {
            email: '',
            pwd: ''
        }
        this.setState({
            creating: false,
            adminData: admin
        })
    }

    changeEmail() {
        const emailInput = this.refs.newEmail.value
        const newAdmin = this.state.adminData
        newAdmin.email = emailInput
        this.setState({
            adminData: newAdmin
        })
    }
    
    changePwd() {
        const pwdInput = this.refs.newPwd.value
        const newAdmin = this.state.adminData
        newAdmin.pwd = pwdInput
        this.setState({
            adminData: newAdmin
        })
    }

    newAdmin() {
        const that = this
        axios.get('/api/user')
            .then(function(res) {
                const [filted] = res.filter(item => {
                    return item.email == that.state.adminData.email
                })
                if (filted) {
                    that.setState({
                        hasAccount: 'Existed Admin User'
                    })
                }else {
                    const formData = that.state.adminData
                    axios.post('/api/user', formData)
                    window.alert('New admin has been created.')
                    that.props.history.push('/home')
                    that.props.history.push('/home/cont')
                }
            })
    }

    deleteUser(item) {
        const _id = item.id
        const email = item.email
        const forsure = confirm('Are you sure to delete the user: ' + email)
        if (forsure) {
            axios.get(`/api/user/${_id}`)
            window.alert('User: ' + email + ' has been deleted')
            that.props.history.push('/home')
            that.props.history.push('/home/cont')
        }else {
            return
        }
    }

    componentWillMount() {
        const that = this
        axios.get('/api/session')
            .then(function(res) {
                const [user] = res
                if (user.identity === 'admin') {
                    that.setState({
                        isRoot: false
                    })
                }else {
                    axios.get('/api/user')
                        .then(function(resp) {
                            const filted = resp.filter(item => {
                                item.time = item.time.split('',10).join('')
                                return item
                            })
                            that.setState({
                                isRoot: true,
                                adminList: filted
                            })
                        })
                        .catch(function(err) {
                            window.alert('Something wrong with the connection, please try later.')
                            that.props.history.push('/home')
                            that.props.history.push('/home/cont')
                        })
                }
            })
            .catch(function(err) {
                window.alert('Something wrong with the connection, please try later.')
                that.props.history.push('/home')
                that.props.history.push('/home/cont')
            })
    }

    render() {
    return <div className="container">
    {this.props.contActive}
    <div className="page-header"></div>
    <div className="panel panel-info">
        <div className="panel-heading">
            <h1 className="panel-title"><strong> Contributor </strong></h1>
        </div>
        <div className="panel-body">
            <p><strong> Users Permissions </strong></p>
            <div className="table-responsive">
                <table className="table table-striped table-condensed table-bordered">
                    <thead>
                        <tr>
                            <th>User</th>
                            <th>Details</th>
                            <th>Commit</th>
                            <th>Confirm</th>
                            <th>Pass</th>
                            <th>Delete</th>
                        </tr>
                    </thead>
                    <tbody>
                        <tr>
                            <td>Admin</td>
                            <td><span className="glyphicon glyphicon-ok"></span></td>
                            <td><span className="glyphicon glyphicon-ok"></span></td>
                            <td><span className="glyphicon glyphicon-ok"></span></td>
                            <td><span className="glyphicon glyphicon-ban-circle"></span></td>
                            <td><span className="glyphicon glyphicon-ok"></span></td>
                        </tr>
                        <tr>
                            <td>Root</td>
                            <td><span className="glyphicon glyphicon-ok"></span></td>
                            <td><span className="glyphicon glyphicon-ok"></span></td>
                            <td><span className="glyphicon glyphicon-ban-circle"></span></td>
                            <td><span className="glyphicon glyphicon-ok"></span></td>
                            <td><span className="glyphicon glyphicon-ok"></span></td>
                        </tr>
                    </tbody>
                </table>
            </div>
            {this.state.isRoot?<div>
                <p><strong> Admin Users List </strong></p>
                <div className="table-responsive">
                    <table className="table table-striped table-condensed table-bordered">
                        <thead>
                            <tr>
                                <th>Email Address</th>
                                <th>Created Time</th>
                                <th>Delete User</th>
                            </tr>
                        </thead>
                        <tbody>
                            {this.state.adminList.map(item => <tr key={item.id}>
                                <td>{item.email}</td>
                                <td>{item.time}</td>
                            <td>{this.state.creating?null:<button type="button" title="delete user" className="btn btn-danger btn-xs" onClick={() =>this.deleteUser(item)}><span className="glyphicon glyphicon-remove"></span></button>}</td>
                            </tr>)}
                        </tbody>
                    </table>
                </div>
                {this.state.creating?null:<button className="btn btn-success" onClick={() =>this.signUpPageShow()}>New Admin Sign up for MIS</button>}
            </div>:null}
            {this.state.creating?<div id={ Contcss.fixedpage } className="container">
                <div id={ Contcss.signpage } className="panel panel-default">
                    <div className="panel-body">
                        <div className="page-header">
                        <button className="btn btn-danger pull-right" onClick={() =>this.signUpPageHide()}><span className="glyphicon glyphicon-remove"></span></button>
                        <h3><strong>New Admin sign up</strong></h3>
                        </div>
                        <form id={ Contcss.newform } method="POST">
                            <div className="form-group">
                                <label>Email address</label>
                                <input type="email" className="form-control" required placeholder="Email" value={this.state.adminData.email} onChange={() => this.changeEmail()} ref='newEmail'/>
                                {this.state.hasAccount?<p className="text-danger">{this.state.hasAccount}</p>:null}
                            </div>
                            <div className="form-group">
                                <label>Password</label>
                                <input type="password" className="form-control" required placeholder="Password" value={this.state.adminData.pwd} onChange={() => this.changePwd()} ref='newPwd'/>
                            </div>
                            <button type="submit" className="btn btn-warning"  onClick={() =>this.newAdmin()}>Sign up</button>
                        </form>
                    </div>
                </div>
            </div>:null}
        </div>
    </div>
</div>
  }
}

// mis-vue/src/components/Cont.vue
<template>
    <div class="container">
        <div class="page-header"></div>
        <div class="panel panel-info">
            <div class="panel-heading">
                <h1 class="panel-title"><strong> Contributor </strong></h1>
            </div>
            <div class="panel-body">
                <p><strong> Users Permissions </strong></p>
                <div class="table-responsive">
                    <table class="table table-striped table-condensed table-bordered">
                        <thead>
                            <tr>
                                <th>User</th>
                                <th>Details</th>
                                <th>Commit</th>
                                <th>Confirm</th>
                                <th>Pass</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr>
                                <td>Admin</td>
                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                <td><span class="glyphicon glyphicon-ban-circle"></span></td>
                                <td><span class="glyphicon glyphicon-ok"></span></td>
                            </tr>
                            <tr>
                                <td>Root</td>
                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                <td><span class="glyphicon glyphicon-ban-circle"></span></td>
                                <td><span class="glyphicon glyphicon-ok"></span></td>
                                <td><span class="glyphicon glyphicon-ok"></span></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                <template v-if="isRoot">
                <p><strong> Admin Users List </strong></p>
                <div class="table-responsive">
                    <table class="table table-striped table-condensed table-bordered">
                        <thead>
                            <tr>
                                <th>Email Address</th>
                                <th>Created Time</th>
                                <th>Delete User</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="item of adminList" :key="item.id">
                                <td>{{ item.email }}</td>
                                <td>{{ item.time }}</td>
                                <td><button @click.prevent="deleteUser(item.id, item.email)" type="button" title="delete user" class="btn btn-danger btn-xs"><span class="glyphicon glyphicon-remove"></span></button></td>
                            </tr>
                        </tbody>
                    </table>
                </div>
                </template>
                <button v-show="isRoot&&!creating" class="btn btn-success"  @click.prevent="signUpPageShow">New Admin Sign up for MIS</button>
                <div id="fixedpage" class="container">
                    <div v-show="creating" id="signpage" class="panel panel-default">
                        <div class="panel-body">
                            <div class="page-header">
                            <button class="btn btn-danger pull-right" @click.prevent="signUpPageHide"><span class="glyphicon glyphicon-remove"></span></button>
                            <h3><strong>New Admin sign up</strong></h3>
                            </div>
                            <form id="newform" method="POST" @submit.prevent="newAdmin">
                                <div class="form-group">
                                    <label>Email address</label>
                                    <input type="email" class="form-control" v-model="adminData.email" required placeholder="Email">
                                    <p v-show="hasAccount" class="text-danger">{{ hasAccount }}</p>
                                </div>
                                <div class="form-group">
                                    <label>Password</label>
                                    <input type="password" class="form-control" v-model="adminData.pwd" required placeholder="Password">
                                </div>
                                <button type="submit" class="btn btn-warning">Sign up</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import axios from 'axios'

export default {
    data () {
        return {
            isRoot: true,
            creating: false,
            adminList: [],
            hasAccount: '',
            adminData: {
                email: '',
                pwd: ''
            }
        }
    },
    async beforeRouteEnter(to, from, next) {
        try {
            const [user] = await axios.get('/api/session')
            if (user.identity === 'admin') {
                next(vm => {
                    vm.isRoot = false
                    vm.$emit('contActive')
                })
            }else {
                const users = await axios.get('/api/user')
                const filted = users.filter(item => {
                    item.time = item.time.split('',10).join('')
                    return item
                })
                next(vm => {
                    vm.isRoot = true
                    vm.adminList = filted
                    vm.$emit('contActive')
                })
            }
        } catch (err) {
            next(vm => {
                vm.$router.push('/')
            })
        }
    },
    methods: {
        signUpPageShow () {
            return this.creating = true
        },
        signUpPageHide () {
            return this.creating = false
        },
        newAdmin: _.debounce(async function () {
            const users = await axios.get('/api/user')
            const [filted] = users.filter(item => {
                return item.email == this.adminData.email
            })
            if (filted) {
                this.hasAccount = 'Existed Admin User'
            }else {
                const formData = this.adminData
                await axios.post('/api/user', formData)
                window.alert('New admin has been created.')
            }
        }),
        async deleteUser(_id, email) {
            const forsure = confirm('Are you sure to delete the user: ' + email)
            if (forsure) {
                await axios.get(`/api/user/${_id}`)
                window.alert('User: ' + email + ' has been deleted')
                window.location.reload()
            }else {
                return
            }
        }
    }
}
</script>

<style>
#signpage {
    margin-top: 10px;
    margin: 0 auto;
    max-width: 400px;
    min-width: 280px;
}
#newform {
    max-width: 330px;
    padding: 15px;
    margin: 0 auto;
}
#fixedpage {
    position: fixed;
    top: 160px;
    left: 0px;
    width: 100%;
}
</style>
