// mis-react/src/components/Detail.jsx
import React from 'react'
import axios from 'axios'
import Detailcss from '../css/detail.scss'

export default class Detail extends React.Component{
    constructor(props) {
        super(props)
        this.state = {
            partsData: [],
            dataDetail: {},
            newData: {
                original: '',
                material: '',
                vandor: '',
                description: '',
                marks: ''
            },
            isRoot: false,
            editing: false,
            viewing: false,
            creating: false,
            editingUser: {},
            exists: ''
        }
    }

    toEdit(item) {
        item.marks = item.marks == 'null'?'':item.marks
        this.setState({
            dataDetail: item,
            viewing: false,
            creating: false,
            editing: true
        })
    }

    notEdit() {
        this.setState({
            editing: false
        })
    }

    toView(item) {
        item.marks = item.marks == 'null'?'':item.marks
        this.setState({
            dataDetail: item,
            viewing: true,
            creating: false,
            editing: false
        })
    }

    notView() {
        this.setState({
            viewing: false
        })
    }

    toCreate() {
        this.setState({
            newData: {},
            viewing: false,
            editing: false,
            creating: true
        })
    }

    notCreate() {
        this.setState({
            creating: false,
            exists: ''
        })
    }

    changeOriginal() {
        const dataDetail = this.state.dataDetail
        const ori = this.refs.original.value
        dataDetail.original = ori
        this.setState({
            dataDetail: dataDetail
        })
    }

    changeMaterial() {
        const dataDetail = this.state.dataDetail
        const mat = this.refs.material.value
        dataDetail.material = mat
        this.setState({
            dataDetail: dataDetail
        })
    }

    changeVandor() {
        const dataDetail = this.state.dataDetail
        const van = this.refs.vandor.value
        dataDetail.vandor = van
        this.setState({
            dataDetail: dataDetail
        })
    }

    changeDescription() {
        const dataDetail = this.state.dataDetail
        const des = this.refs.description.value
        dataDetail.description = des
        this.setState({
            dataDetail: dataDetail
        })
    }

    changeMarks() {
        const dataDetail = this.state.dataDetail
        const mar = this.refs.marks.value
        dataDetail.marks = mar
        this.setState({
            dataDetail: dataDetail
        })
    }

    createOriginal() {
        const newData = this.state.newData
        const ori = this.refs.newOriginal.value
        newData.original = ori
        this.setState({
            newData: newData
        })
    }

    createMaterial() {
        const newData = this.state.newData
        const mat = this.refs.newMaterial.value
        newData.material = mat
        this.setState({
            newData: newData
        })
    }

    createVandor() {
        const newData = this.state.newData
        const van = this.refs.newVandor.value
        newData.vandor = van
        this.setState({
            newData: newData
        })
    }

    createDescription() {
        const newData = this.state.newData
        const des = this.refs.newDescription.value
        newData.description = des
        this.setState({
            newData: newData
        })
    }

    createMarks() {
        const newData = this.state.newData
        const mar = this.refs.newMarks.value
        newData.marks = mar
        this.setState({
            newData: newData
        })
    }

    addData(e) {
        e.preventDefault()
        const that = this
        axios.get('/api/partsdata')
            .then(function(res) {
                const [exist] = res.filter(item => {
                    return item.original == that.state.newData.original||item.material == that.state.newData.material
                })
                if (exist) {
                    return that.setState({
                        exists: 'Data exists.'
                    })
                }
                if (!that.state.newData.marks) {
                    const data = that.state.newData
                    data.marks = null
                    that.setState({
                        newData: data
                    })
                }
                const formData = that.state.newData
                axios.post('/api/partsdata', formData)
                    .then(function(resp) {
                        if (resp) {
                            window.alert('New data saved')
                            that.props.history.push('/home')
                            that.props.history.push('/home/detail')
                        }
                    })
                    .catch(function(err) {
                        window.alert('New data can not be saved, please try later.')
                    })
            })
            .catch(function(err) {
                window.alert('Something wrong with the connection, please try later.')
            })
    }

    toConfirm (item) {
        const _id =item.id
        const num = item.original
        const that = this
        const forsure = confirm('Confirm for the original: ' + num)
        if (forsure) {
            const [dataDetail] = that.state.partsData.filter(item => {
                return item.id == _id
            })
            axios.post(`/api/partsdata/${_id}`, dataDetail)
                .then(function(res) {
                    window.alert('One more data confirmed')
                    that.props.history.push('/home')
                    that.props.history.push('/home/detail')
                })
                .catch(function(err) {
                    window.alert('Something wrong with the connection, please try later.')
                })
        }else {
            return
        }
    }

    toDelete (item) {
        const _id =item.id
        const num = item.original
        const that = this
        const forsure = confirm('Are you sure to delete the original: ' + num)
        if (forsure) {
            axios.get(`/api/partsdata/${_id}`)
                .then(function(res) {
                    window.alert('One data deleted')
                    that.props.history.push('/home')
                    that.props.history.push('/home/detail')
                })
                .catch(function(err) {
                    window.alert('Something wrong with the connection, please try later.')
                })
        }else {
            return
        }
    }

    toSubmit () {
        const formData = this.state.dataDetail
        const _id = formData.id
        formData.fromSub = this.state.isRoot===true?false:true
        this.notEdit()
        const that = this
        axios.post(`/api/partsdata/${_id}`, formData)
            .then(function(res) {
                window.alert('One more data updated')
                that.props.history.push('/home')
                that.props.history.push('/home/detail')
            })
            .catch(function(err) {
                window.alert('Something wrong with the connection, please try later.')
            })
    }

    componentDidMount() {
        const that = this
        axios.get('/api/session')
            .then(function(res) {
                const [user] = res
                if (user.identity === 'admin') {
                    axios.get('/api/partsdata')
                        .then(function(resp) {
                            const filted = resp.filter(item => {
                                item.creation = item.creation.split('',10).join('')
                                item.marks = item.marks == 'null'?'':item.marks
                                return item.contributor == user.email
                            })
                            that.setState({
                                partsData: filted,
                                isRoot: false,
                                editingUser: false
                            })
                        })
                }else{
                    axios.get('/api/partsdata')
                        .then(function(resp) {
                            const filted = resp.filter(item => {
                                item.creation = item.creation.split('',10).join('')
                                item.marks = item.marks == 'null'?'':item.marks
                                return item.status == 'active'||item.contributor == user.email
                            })
                            that.setState({
                                partsData: filted,
                                isRoot: true,
                                editingUser: user
                            })
                        })
                }
            })
            .catch (function(err) {
                that.props.history.push('/home')
            })
    }

    render() {
    return <div>
    <div className="container">
    {this.props.detailActive}
        <div className="page-header"></div>
        <div className="panel panel-default">
            <div className="panel-heading">
                <h1 className="panel-title"><strong> Details </strong><button type="button" className="btn btn-success btn-xs pull-right" onClick={() =>this.toCreate()}>Create new data</button></h1>
            </div>
            <div className="table-responsive">
                <table className="table table-striped table-condensed table-bordered">
                    <thead>
                        <tr>
                            <th>Original NO.</th>
                            <th>Material NO.</th>
                            <th>Description</th>
                            <th>Vandor</th>
                            <th>Operations Buttons</th>
                        </tr>
                    </thead>
                    <tbody>
                        {this.state.partsData.map(item =><tr key={item.id}>
                            <td>{item.original}</td>
                            <td>{item.material}</td>
                            <td>{item.description}</td>
                            <td>{item.vandor}</td>
                            <td>
                                <div className="btn-group btn-group-xs">
                                    {this.state.viewing?null:<button type="button" title="details" className="btn btn-default" onClick={ () =>this.toView(item)}><span className="glyphicon glyphicon-option-horizontal"></span></button>}
                                    {this.state.editing?null:<button type="button" title="commit" className="btn btn-primary" onClick={ () =>this.toEdit(item)}><span className="glyphicon glyphicon-pencil"></span></button>}
                                    {this.state.isRoot?<button type="button" title="confirm" className="btn btn-success" onClick={ () =>this.toConfirm(item)}><span className="glyphicon glyphicon-check"></span></button>:null}
                                    <button type="button" title="delete" className="btn btn-danger" onClick={ () =>this.toDelete(item)}><span className="glyphicon glyphicon-remove"></span></button>
                                </div>
                            </td>
                        </tr>)}
                        </tbody>
                </table>
            </div>
            
        </div>
    </div>
    {this.state.editing?<div id={ Detailcss.item1 } className="container">
        <div id={ Detailcss.outter1 } className="panel panel-primary">
            <div className="panel-heading">
                <div className="page-header">
                <button className="btn btn-danger pull-right" onClick={ () =>this.notEdit() }><span className="glyphicon glyphicon-remove"></span></button>
                <h3><strong>Editing item</strong></h3>
                </div>
            </div>
            <div className="panel-body">
                <form onSubmit={(e) =>this.toSubmit(e)}>
                    <div className="form-group">
                        <div className="row">
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Original NO. </strong></span>
                                    <input type="text" className="form-control" required value={this.state.dataDetail.original} onChange={() =>this.changeOriginal()} ref='original'/>
                                </div>
                            </div>
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Material NO. </strong></span>
                                    <input type="text" className="form-control" required value={this.state.dataDetail.material} onChange={() =>this.changeMaterial()} ref='material'/>
                                </div>
                            </div>
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Vandor </strong></span>
                                    <input type="text" className="form-control" required value={this.state.dataDetail.vandor} onChange={() =>this.changeVandor()} ref='vandor'/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="form-group">
                        <label>Description</label>
                        <input type="text" className="form-control" required value={this.state.dataDetail.description} onChange={() =>this.changeDescription()} ref='description'/>
                    </div>
                    <div className="form-group">
                        <label>Marks</label>
                        <input type="text" className="form-control" value={this.state.dataDetail.marks} onChange={() =>this.changeMarks()} ref='marks'/>
                    </div>
                    <button type="submit" className="btn btn-warning pull-right"><strong> Submit </strong></button>
                </form>
            </div>
        </div>
    </div>:null}
    {this.state.viewing?<div id={ Detailcss.item2 } className="container">
        <div id={ Detailcss.outter2 } className="panel panel-default">
            <div className="panel-heading">
                <div className="page-header">
                <button className="btn btn-danger pull-right" onClick={ () =>this.notView() }><span className="glyphicon glyphicon-remove"></span></button>
                <h3><strong>Item details</strong></h3>
                </div>
            </div>
            <div className="panel-body">
                <form method="POST">
                    <div className="form-group">
                        <div className="row">
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Original NO. </strong></span>
                                    <input type="text" className="form-control" disabled placeholder={this.state.dataDetail.original}/>
                                </div>
                            </div>
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Material NO. </strong></span>
                                    <input type="text" className="form-control" disabled placeholder={this.state.dataDetail.material}/>
                                </div>
                            </div>
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Vandor </strong></span>
                                    <input type="text" className="form-control" disabled placeholder={this.state.dataDetail.vandor}/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="form-group">
                        <label>Description</label>
                        <input type="text" className="form-control" disabled placeholder={this.state.dataDetail.description}/>
                    </div>
                    <div className="form-group">
                        <label>Marks</label>
                        <input type="text" className="form-control" disabled placeholder={this.state.dataDetail.marks}/>
                    </div>
                    <div className="form-group">
                        <div className="row">
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Status </strong></span>
                                    <input type="text" className="form-control" disabled placeholder={this.state.dataDetail.status}/>
                                </div>
                            </div>
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Contributor </strong></span>
                                    <input type="text" className="form-control" disabled placeholder={this.state.dataDetail.contributor}/>
                                </div>
                            </div>
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Creation Time </strong></span>
                                    <input type="text" className="form-control" disabled placeholder={this.state.dataDetail.creation}/>
                                </div>
                            </div>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>:null}
    {this.state.creating?<div id={ Detailcss.item3 } className="container">
        <div id={ Detailcss.outter3 } className="panel panel-success">
            <div className="panel-heading">
                <div className="page-header">
                <button className="btn btn-danger pull-right" onClick={ () =>this.notCreate() }><span className="glyphicon glyphicon-remove"></span></button>
                <h3><strong>Creating New Data</strong></h3>
                </div>
            </div>
            <div className="panel-body">
                <form onSubmit={(e) => this.addData(e)}>
                    <div className="form-group">
                        <div className="row">
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Original NO. </strong></span>
                                    <input type="text" className="form-control" required value={this.state.newData.original} onChange={() => this.createOriginal()} ref='newOriginal'/>
                                </div>
                            </div>
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Material NO. </strong></span>
                                    <input type="text" className="form-control" required value={this.state.newData.material} onChange={() => this.createMaterial()} ref='newMaterial'/>
                                </div>
                            </div>
                            <div className="col-sm-4">
                                <div className="input-group">
                                    <span className="input-group-addon"><strong> Vandor </strong></span>
                                    <input type="text" className="form-control" required value={this.state.newData.vandor} onChange={() => this.createVandor()} ref='newVandor'/>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div className="form-group">
                        <label>Description</label>
                        <input type="text" className="form-control" required value={this.state.newData.description} onChange={() => this.createDescription()} ref='newDescription'/>
                    </div>
                    <div className="form-group">
                        <label>Marks</label>
                        <input type="text" className="form-control" value={this.state.newData.marks} onChange={() => this.createMarks()} ref='newMarks'/>
                    </div>
                    {this.state.exists?<div className="alert alert-danger"><span className="glyphicon glyphicon-alert"></span><strong>{this.state.exists}</strong></div>:null}
                    <button type="submit" className="btn btn-warning pull-right"><strong> Submit </strong></button>
                </form>
            </div>
        </div>
    </div>:null}
</div>
  }
}

// mis-vue/src/components/Detail.vue
<template>
    <div>
        <div class="container">
            <div class="page-header"></div>
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h1 class="panel-title"><strong> Details </strong><button @click.prevent="toCreate" type="button" class="btn btn-success btn-xs pull-right">Create new data</button></h1>
                </div>
                <div class="table-responsive">
                    <table class="table table-striped table-condensed table-bordered">
                        <thead>
                            <tr>
                                <th>Original NO.</th>
                                <th>Material NO.</th>
                                <th>Description</th>
                                <th>Vandor</th>
                                <th>Operations Buttons</th>
                            </tr>
                        </thead>
                        <tbody>
                            <tr v-for="item of partsData" :key="item.id">
                                <td>{{ item.original }}</td>
                                <td>{{ item.material }}</td>
                                <td>{{ item.description }}</td>
                                <td>{{ item.vandor }}</td>
                                <td>
                                    <div class="btn-group btn-group-xs">
                                        <button @click.prevent="toView(item.id)" type="button" title="details" class="btn btn-default"><span class="glyphicon glyphicon-option-horizontal"></span></button>
                                        <button @click.prevent="toEdit(item.id)" type="button" title="commit" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span></button>
                                        <button @click.prevent="toConfirm(item.id, item.original)" v-if="!isRoot" type="button" title="confirm" class="btn btn-success"><span class="glyphicon glyphicon-check"></span></button>
                                        <button @click.prevent="toDelete(item.id, item.original)" type="button" title="delete" class="btn btn-danger"><span class="glyphicon glyphicon-remove"></span></button>
                                    </div>
                                </td>
                            </tr>
                            </tbody>
                    </table>
                </div>
                
            </div>
        </div>
        <div v-show="editing" id="item1" class="container">
            <div id="outter1" class="panel panel-primary">
                <div class="panel-heading">
                    <div class="page-header">
                    <button @click.prevent="notEdit" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-remove"></span></button>
                    <h3><strong>Editing item</strong></h3>
                    </div>
                </div>
                <div class="panel-body">
                    <form method="POST" @submit.prevent="toSubmit">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Original NO. </strong></span>
                                        <input type="text" class="form-control" required v-model="dataDetail.original">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Material NO. </strong></span>
                                        <input type="text" class="form-control" required v-model="dataDetail.material">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Vandor </strong></span>
                                        <input type="text" class="form-control" required v-model="dataDetail.vandor">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <input type="text" class="form-control" required v-model="dataDetail.description">
                        </div>
                        <div class="form-group">
                            <label>Marks</label>
                            <input type="text" class="form-control" v-model="dataDetail.marks">
                        </div>
                        <button type="submit" class="btn btn-warning pull-right"><strong> Submit </strong></button>
                    </form>
                </div>
            </div>
        </div>
        <div v-show="viewing" id="item2" class="container">
            <div id="outter2" class="panel panel-default">
                <div class="panel-heading">
                    <div class="page-header">
                    <button @click.prevent="notView" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-remove"></span></button>
                    <h3><strong>Item details</strong></h3>
                    </div>
                </div>
                <div class="panel-body">
                    <form method="POST">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Original NO. </strong></span>
                                        <input type="text" class="form-control" disabled v-model="dataDetail.original">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Material NO. </strong></span>
                                        <input type="text" class="form-control" disabled v-model="dataDetail.material">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Vandor </strong></span>
                                        <input type="text" class="form-control" disabled v-model="dataDetail.vandor">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <input type="text" class="form-control" disabled v-model="dataDetail.description">
                        </div>
                        <div class="form-group">
                            <label>Marks</label>
                            <input type="text" class="form-control" disabled v-model="dataDetail.marks">
                        </div>
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Status </strong></span>
                                        <input type="text" class="form-control" disabled v-model="dataDetail.status">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Contributor </strong></span>
                                        <input type="text" class="form-control" disabled v-model="dataDetail.contributor">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Creation Time </strong></span>
                                        <input type="text" class="form-control" disabled v-model="dataDetail.creation">
                                    </div>
                                </div>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
        <div v-show="creating" id="item3" class="container">
            <div id="outter3" class="panel panel-success">
                <div class="panel-heading">
                    <div class="page-header">
                    <button @click.prevent="notCreate" class="btn btn-danger pull-right"><span class="glyphicon glyphicon-remove"></span></button>
                    <h3><strong>Creating New Data</strong></h3>
                    </div>
                </div>
                <div class="panel-body">
                    <form method="POST" @submit.prevent="addData">
                        <div class="form-group">
                            <div class="row">
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Original NO. </strong></span>
                                        <input type="text" class="form-control" required v-model="newData.original">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Material NO. </strong></span>
                                        <input type="text" class="form-control" required v-model="newData.material">
                                    </div>
                                </div>
                                <div class="col-sm-4">
                                    <div class="input-group">
                                        <span class="input-group-addon"><strong> Vandor </strong></span>
                                        <input type="text" class="form-control" required v-model="newData.vandor">
                                    </div>
                                </div>
                            </div>
                        </div>
                        <div class="form-group">
                            <label>Description</label>
                            <input type="text" class="form-control" required v-model="newData.description">
                        </div>
                        <div class="form-group">
                            <label>Marks</label>
                            <input type="text" class="form-control" v-model="newData.marks">
                        </div>
                        <div class="alert alert-danger" v-show="exists"><span class="glyphicon glyphicon-alert"></span><strong>{{ exists }}</strong></div>
                        <button type="submit" class="btn btn-warning pull-right"><strong> Submit </strong></button>
                    </form>
                </div>
            </div>
        </div>
    </div>
</template>

<script>
import axios from 'axios'

export default {
    data () {
        return {
            partsData: [],
            dataDetail: {},
            newData: {},
            isRoot: false,
            editing: false,
            viewing: false,
            creating: false,
            editingUser: {},
            exists: ''
        }
    },
    async beforeRouteEnter(to, from, next) {
        try {
            const [user] = await axios.get('/api/session')
            if (user.identity === 'admin') {
                const res = await axios.get('/api/partsdata')
                const filted = res.filter(item => {
                    item.creation = item.creation.split('',10).join('')
                    item.marks = item.marks == 'null'?'':item.marks
                    return item.contributor == user.email
                })
                next(vm => {
                    vm.partsData = filted
                    vm.isRoot = false
                    vm.editingUser = user
                    vm.$emit('detailActive')
                })
            }else{
                const res = await axios.get('/api/partsdata')
                const filted = res.filter(item => {
                    item.creation = item.creation.split('',10).join('')
                    item.marks = item.marks == 'null'?'':item.marks
                    return item.status == 'closed'
                })
                next(vm =>{
                    vm.partsData = filted
                    vm.isRoot = true
                    vm.editingUser = user
                    vm.$emit('detailActive')
                })
            }
        } catch (err) {
            next(vm => {
                vm.$router.push('/')
            })
        }
    },
    methods: {
        toEdit (_id) {
            const [dataDetail] = this.partsData.filter(item => {
                return item.id == _id
            })
            dataDetail.marks = dataDetail.marks == 'null'?'':dataDetail.marks
            this.dataDetail = dataDetail
            this.viewing = false
            this.creating = false
            this.editing = true
        },
        notEdit () {
            this.editing = false
        },
        toView (_id) {
            const [dataDetail] = this.partsData.filter(item => {
                return item.id == _id
            })
            dataDetail.marks = dataDetail.marks == 'null'?'':dataDetail.marks
            this.dataDetail = dataDetail
            this.editing = false
            this.creating = false
            this.viewing = true
        },
        notView () {
            this.viewing = false
        },
        toCreate () {
            this.newData = {}
            this.viewing = false
            this.editing = false
            this.creating = true
        },
        notCreate () {
            this.creating = false
            this.exists = ''
        },
        async addData () {
            const exists = await axios.get('/api/partsdata')
            const [exist] = exists.filter(item => {
                return item.original == this.newData.original||item.material == this.newData.material
            })
            if (exist) {
                return this.exists = 'Data exists'
            }
            if (!this.newData.marks) {
                this.newData.marks = null
            }
            const formData = this.newData
            const data = await axios.post('/api/partsdata', formData)
            if (data) {
                window.alert('New data saved')
                window.location.reload()
            }
        },
        async toConfirm (_id, num) {
            const forsure = confirm('Confirm for the original: ' + num)
            if (forsure) {
                const [dataDetail] = this.partsData.filter(item => {
                    return item.id == _id
                })
                await axios.post(`/api/partsdata/${_id}`, dataDetail)
                window.alert('One more data confirmed')
                window.location.reload()
            }else {
                return
            }
        },
        async toDelete (_id, num) {
            const forsure = confirm('Are you sure to delete the original: ' + num)
            if (forsure) {
                const res = await axios.get(`/api/partsdata/${_id}`)
                window.alert('One data deleted')
                window.location.reload()
            }else {
                return
            }
        },
        async toSubmit () {
            const formData = this.dataDetail
            const _id = formData.id
            formData.fromSub = this.isRoot===true?false:true
            this.notEdit()
            await axios.post(`/api/partsdata/${_id}`, formData)
            window.alert('One more data updated')
            window.location.reload()
        }
    }
}
</script>

<style>
#item1, #item2, #item3 {
    position: fixed;
    top: 80px;
    left: 0px;
    width: 100%;
}
#outter1, #outter2, #outter3 {
    margin-top: 10px;
    margin: 0 auto;
    max-width: 950px;
    min-width: 280px;
}
</style>
