// mis-vue/src/components/Login.vue
<template>
  <div class="container">
    <form class="form-signin" @submit.prevent="loggedin">
      <div class="alert alert-danger" v-show="errorMsg"><span class="glyphicon glyphicon-alert"></span><strong> {{ errorMsg }}</strong></div>
      <h2 class="form-signin-heading"><strong>Sign in to MIS</strong></h2>
      <label for="inputEmail">Email address</label>
      <input v-model="formData.email" type="email" class="form-control" placeholder="Email" required autofocus>
      <label for="inputPassword">Password</label>
      <input v-model="formData.pwd" type="password" class="form-control" placeholder="Password" required>
      <button class="btn btn-lg btn-warning btn-block" type="submit">Sign in</button>
    </form>
    <div class="foottext">
      <h3>Fisheep Studio</h3>
      <img :src="img" class="img-rounded" alt="LOGO">
      <p><small>REV.D _July 2018</small></p>
      <p><small>@V _1.0/EN</small></p>
    </div>
  </div>
</template>

<script>
import img from '../../static/images/fisheeplogo.png'
import axios from 'axios'
import _ from 'lodash'

export default {
  data () {
    return {
      img,
      formData: {
        email: '',
        pwd: ''
      },
      errorMsg: ''
    }
  },
  methods: {
    loggedin: _.debounce( async function () {
      try {
        const formData = this.formData
        const res = await axios.post('/api/session', formData)
        if (!res[0]) {
            this.errorMsg = 'Invalid Email or Password'
            this.formData.pwd = ''
            return
        }
        this.$router.push('/')
      } catch (err) {
        const {status} = err
        switch (status) {
          case 500:
            this.errorMsg = 'Server Error. Try Later.'
            break
        }
      }
    }, 500)
  }
}
</script>

<style>
body {
  padding-top: 40px;
  padding-bottom: 40px;
}
.form-signin {
  max-width: 330px;
  padding: 15px;
  margin: 0 auto;
}
.form-signin-heading {
  margin-bottom: 10px;
  text-align: center;
}
.foottext {
  text-align: center;
  margin-top: 60px;
}
.img-rounded {
  height: 45px;
}
.form-signin .form-control {
  position: relative;
  height: auto;
  -webkit-box-sizing: border-box;
     -moz-box-sizing: border-box;
          box-sizing: border-box;
  padding: 10px;
  font-size: 16px;
}
.form-signin .form-control:focus {
  z-index: 2;
}
.form-signin input[type="email"] {
  margin-bottom: -1px;
  border-bottom-right-radius: 0;
  border-bottom-left-radius: 0;
}
.form-signin input[type="password"] {
  margin-bottom: 10px;
  border-top-left-radius: 0;
  border-top-right-radius: 0;
}
</style>

// mis-react/src/components/Login.jsx
import React from 'react'
import axios from 'axios'
import Logo from '../static/images/fisheeplogo.png'
import Logincss from '../css/login.scss'

export default class Login extends React.Component{
  constructor(props) {
    super(props)
    this.state = {
      email: '',
      pwd: '',
      errorMsg: ''
    }
  }

  login(e) {
    e.preventDefault()
    const formData = {
      email: this.state.email,
      pwd: this.state.pwd
    }
    const that = this
    axios.post('/api/session', formData)
      .then(function(res){
        if (!res[0]) {
          return that.setState({
            errorMsg: 'Invalid Email or Password',
            pwd: ''
          })
        }
        return that.props.history.push('/home')
      })
      .catch(function(err){
        const {status} = err
        switch (status) {
          case 500:
            that.setState({
              errorMsg: 'Server Error. Try Later.'
            })
            break
          case 504:
            that.setState({
              errorMsg: 'Connection timeout.'
            })
            break
        }
      })
  }

  emailChange() {
    const inputEmail = this.refs.email.value
    this.setState({
      email: inputEmail
    })
  }

  pwdChange() {
    const inputPwd = this.refs.pwd.value
    this.setState({
      pwd: inputPwd
    })
  }
  
  render() {
    return <div className="container">
    <form className={ Logincss.formsignin } onSubmit={ (e)=>this.login(e) }>
      {this.state.errorMsg==''?null:<div className="alert alert-danger"><span className="glyphicon glyphicon-alert"></span><strong> {this.state.errorMsg}</strong></div>}
      <h2 className={ Logincss.formsigninheading }><strong>Sign in to MIS</strong></h2>
      <label>Email address</label>
      <input type="email" className="form-control" placeholder="Email" required autoFocus value={this.state.email} onChange={ () => this.emailChange() } ref='email'/>
      <label>Password</label>
      <input type="password" className="form-control" placeholder="Password" required value={this.state.pwd} onChange={ () => this.pwdChange() } ref='pwd'/>
      <button className="btn btn-lg btn-warning btn-block" type="submit">Sign in</button>
    </form>
    <div className={ Logincss.foottext }>
      <h3>Fisheep Studio</h3>
      <img src={ Logo } className={ Logincss.imgrounded } alt="LOGO" />
      <p><small>REV.D _Aug 2018</small></p>
      <p><small>@V _1.0/EN</small></p>
    </div>
  </div>
  }
}
